export const companyRouterMap = [
    {
        path:'/index',
        redirect:'/company_detail',
        component:()=>import('@/views/Index'),
        children:[
            {
                path:'/company_detail',
                name:'company_detail',
                component:()=>import('@/views/company/CompanyDetail'),
            },
            {
                path:'/post',
                name:'post',
                component:()=>import('@/views/post/Post'),
            },
            {
                path:'/send',
                name:'send',
                component:()=>import('@/views/send/Send'),
            },
        ]
    }
]
